"""init new models(product, order,rating,review,store) and update user model

Revision ID: beb4c20e610d
Revises: bf80fd7a471c
Create Date: 2025-05-06 10:21:24.581818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4c20e610d'
down_revision: Union[str, None] = 'bf80fd7a471c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
