"""Initial migration

Revision ID: ca4f21c313f2
Revises: ccc635dc496e
Create Date: 2025-05-03 00:18:06.004208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4f21c313f2'
down_revision: Union[str, None] = 'ccc635dc496e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('Male', 'Female', name='gender'),
               existing_nullable=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
