"""Initial migration

Revision ID: ccc635dc496e
Revises: f31d2f1afd93
Create Date: 2025-05-02 19:17:52.437776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccc635dc496e'
down_revision: Union[str, None] = 'f31d2f1afd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Male', 'Female', name='gender'),
               existing_nullable=True)
    # ### end Alembic commands ###
