"""init new models(product, order,rating,review,store) and update user model

Revision ID: e288f2bf7ce8
Revises: d296368e9132
Create Date: 2025-05-06 10:49:47.109803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e288f2bf7ce8'
down_revision: Union[str, None] = 'd296368e9132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
