"""update review table

Revision ID: f021662ad22f
Revises: e288f2bf7ce8
Create Date: 2025-05-06 10:50:57.429423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f021662ad22f'
down_revision: Union[str, None] = 'e288f2bf7ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating_id', sa.Integer(), nullable=False, foreign_key='ratings.id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating_id')
    # ### end Alembic commands ###
